name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get -y install g++ flex bison nasm build-essential gcc-multilib libfl-dev
      
    - name: Compile
      run: make
      
    - name: Run test
      run: make test
      
    - name: Fail test
      run: echo "282" > test/test_arithmetic.out && make test
