name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && apt-get -y install g++ flex bison nasm build-essential gcc-multilib libfl-dev
      
    - name: Compile without flex+bison commands
      run: sed -i 's/flex /# flex /g' Makefile && sed -i 's/bison /# bison /g' Makefile && make no-flex-bison-clean && make && sed -i 's/# flex/flex/g' Makefile && sed -i 's/# bison/bison/g' Makefile 
      
    - name: Compile All
      run: make clean && make
      
    - name: Run test
      run: make test
